/*
SCRIPT DE CRIAÇÃO DA BASE.
AUTOR: EDGAR BRASIL SOVINSKI
DATA: 01/09/2017
*/

USE MASTER
GO

IF EXISTS(SELECT * FROM SYS.DATABASES WHERE NAME = 'VENDAS')	
   DROP DATABASE [VENDAS]
GO

IF NOT EXISTS(SELECT * FROM SYS.DATABASES WHERE NAME = 'VENDAS')	
    CREATE DATABASE VENDAS
GO

IF NOT EXISTS(SELECT * FROM SYS.DATABASES WHERE NAME = 'VENDAS')	
    RETURN

USE VENDAS
GO

/*
CLIENTE
*/
IF (OBJECT_ID('CLIENTE') IS NULL)
BEGIN
	CREATE TABLE CLIENTE (
		SEQ_CLIENTE INT NOT NULL,
		DS_NOME VARCHAR(100) NOT NULL
	CONSTRAINT [PK_CLIENTE] PRIMARY KEY CLUSTERED 
	(
	[SEQ_CLIENTE] ASC
	)
	WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
	)
END
GO

IF OBJECT_ID('CLIENTE_GEN', 'SO') IS NULL 	
BEGIN
	CREATE SEQUENCE [DBO].[CLIENTE_GEN] 
		AS [BIGINT]
		START WITH 1
		INCREMENT BY 1
		MINVALUE 1
END
GO

IF (OBJECT_ID('CLIENTE') IS NOT NULL) AND 
   (OBJECT_ID('CLIENTE_GEN', 'SO') IS NOT NULL) AND
   (OBJECT_ID('DEF_SEQ_CLIENTE', 'D') IS NULL)
BEGIN
	ALTER TABLE CLIENTE
		ADD CONSTRAINT DEF_SEQ_CLIENTE DEFAULT (NEXT VALUE FOR CLIENTE_GEN) FOR SEQ_CLIENTE
END	
/*
CLIENTE
*/


/*
MERCADORIA_GRUPO
*/
IF (OBJECT_ID('MERCADORIA_GRUPO') IS NULL)
BEGIN
	CREATE TABLE MERCADORIA_GRUPO (
		SEQ_MERCADORIA_GRUPO INT NOT NULL,
		DS_NOME VARCHAR(255) NOT NULL,
		FG_COBRA_TAXA_SERVICO CHAR(1) DEFAULT 'N' 
	CONSTRAINT [PK_MERCADORIA_GRUPO] PRIMARY KEY CLUSTERED 
	(
	[SEQ_MERCADORIA_GRUPO] ASC
	)
	WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
	)
END
GO

IF OBJECT_ID('MERCADORIA_GRUPO_GEN', 'SO') IS NULL 	
BEGIN
	CREATE SEQUENCE [DBO].[MERCADORIA_GRUPO_GEN] 
		AS [BIGINT]
		START WITH 1
		INCREMENT BY 1
		MINVALUE 1
END
GO

IF (OBJECT_ID('MERCADORIA_GRUPO') IS NOT NULL) AND
   (OBJECT_ID('MERCADORIA_GRUPO_GEN', 'SO') IS NOT NULL) AND
   (OBJECT_ID('DEF_SEQ_MERCADORIA_GRUPO', 'D') IS NULL)
BEGIN
	ALTER TABLE MERCADORIA_GRUPO
		ADD CONSTRAINT DEF_SEQ_MERCADORIA_GRUPO DEFAULT (NEXT VALUE FOR MERCADORIA_GRUPO_GEN) FOR SEQ_MERCADORIA_GRUPO
END

/*
MERCADORIA_GRUPO
*/

/*
MERCADORIA
*/
IF (OBJECT_ID('MERCADORIA') IS NULL)
BEGIN
	CREATE TABLE MERCADORIA (
		SEQ_MERCADORIA INT NOT NULL,
		DS_NOME VARCHAR(255) NOT NULL,
		VR_PRECO FLOAT ,
		QT_ESTOQUE INT NOT NULL, 
		ID_MERCADORIA_GRUPO INT NULL, 
		FG_COBRA_TAXA_SERVICO CHAR(1) NULL DEFAULT 'N',
		FG_VALIDAR_GRUPO CHAR(1) NULL DEFAULT 'N'
	CONSTRAINT [PK_MERCADORIA] PRIMARY KEY CLUSTERED 
	(
	[SEQ_MERCADORIA] ASC
	)
	WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
	)
	END

	ALTER TABLE [dbo].[MERCADORIA] WITH NOCHECK ADD CONSTRAINT [FK_MERCADORIA_MERCADORIA_GRUPO] FOREIGN KEY([ID_MERCADORIA_GRUPO])
	REFERENCES [dbo].[MERCADORIA_GRUPO] ([SEQ_MERCADORIA_GRUPO])
GO

IF OBJECT_ID('MERCADORIA_GEN', 'SO') IS NULL 	
BEGIN
	CREATE SEQUENCE [DBO].[MERCADORIA_GEN] 
		AS [BIGINT]
		START WITH 1
		INCREMENT BY 1
		MINVALUE 1
END
GO

IF (OBJECT_ID('MERCADORIA') IS NOT NULL) AND
   (OBJECT_ID('MERCADORIA_GEN', 'SO') IS NOT NULL) AND
   (OBJECT_ID('DEF_SEQ_MERCADORIA', 'D') IS NULL)
BEGIN
	ALTER TABLE MERCADORIA
		ADD CONSTRAINT DEF_SEQ_MERCADORIA DEFAULT (NEXT VALUE FOR MERCADORIA_GEN) FOR SEQ_MERCADORIA
END
/*
MERCADORIA
*/

/*
VENDA
*/
IF (OBJECT_ID('VENDA') IS NULL)
BEGIN
	CREATE TABLE VENDA (
		SEQ_VENDA INT NOT NULL,
		DT_VENDA DATETIME,
		ID_CLIENTE INT NOT NULL,
		VR_DESCONTO FLOAT,
		PC_TAXA_SERVICO FLOAT,
		VR_TOTAL FLOAT
	CONSTRAINT [PK_VENDA] PRIMARY KEY CLUSTERED 
	(
	[SEQ_VENDA] ASC
	)
	WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
	)

	ALTER TABLE [dbo].[VENDA] WITH NOCHECK ADD CONSTRAINT [FK_VENDA_CLIENTE] FOREIGN KEY([ID_CLIENTE])
	REFERENCES [dbo].[CLIENTE] ([SEQ_CLIENTE])
END
GO

IF OBJECT_ID('VENDA_GEN', 'SO') IS NULL 	
BEGIN
	CREATE SEQUENCE [DBO].[VENDA_GEN] 
		AS [BIGINT]
		START WITH 1
		INCREMENT BY 1
		MINVALUE 1
END
GO

IF (OBJECT_ID('VENDA') IS NOT NULL) AND 
   (OBJECT_ID('VENDA_GEN', 'SO') IS NOT NULL) AND
   (OBJECT_ID('DEF_SEQ_VENDA', 'D') IS NULL)
BEGIN
	ALTER TABLE VENDA
		ADD CONSTRAINT DEF_SEQ_VENDA DEFAULT (NEXT VALUE FOR VENDA_GEN) FOR SEQ_VENDA
END	
/*
VENDA
*/

/*
VENDA_ITEM
*/
IF (OBJECT_ID('VENDA_ITEM') IS NULL)
BEGIN
	CREATE TABLE VENDA_ITEM (
		SEQ_VENDA_ITEM INT NOT NULL,
		ID_VENDA INT NOT NULL,
		ID_MERCADORIA INT NOT NULL,
		QT_VENDIDA INT NOT NULL,
		VD_VALOR FLOAT
	CONSTRAINT [PK_VENDA_ITEM] PRIMARY KEY CLUSTERED 
	(
	[SEQ_VENDA_ITEM] ASC
	)
	WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 90) ON [PRIMARY]
	)

	ALTER TABLE [dbo].[VENDA_ITEM] WITH NOCHECK ADD CONSTRAINT [FK_VENDA_ITEM_VENDA] FOREIGN KEY([ID_VENDA])
	REFERENCES [dbo].[VENDA] ([SEQ_VENDA])

	ALTER TABLE [dbo].[VENDA_ITEM] WITH NOCHECK ADD CONSTRAINT [FK_VENDA_ITEM_MERCADORIA] FOREIGN KEY([ID_MERCADORIA])
	REFERENCES [dbo].[MERCADORIA] ([SEQ_MERCADORIA])
END
GO

IF OBJECT_ID('VENDA_ITEM_GEN', 'SO') IS NULL 	
BEGIN
	CREATE SEQUENCE [DBO].[VENDA_ITEM_GEN] 
		AS [BIGINT]
		START WITH 1
		INCREMENT BY 1
		MINVALUE 1
END
GO

IF (OBJECT_ID('VENDA_ITEM') IS NOT NULL) AND 
   (OBJECT_ID('VENDA_ITEM_GEN', 'SO') IS NOT NULL) AND
   (OBJECT_ID('DEF_SEQ_VENDA_ITEM', 'D') IS NULL)
BEGIN
	ALTER TABLE VENDA_ITEM
		ADD CONSTRAINT DEF_SEQ_VENDA_ITEM DEFAULT (NEXT VALUE FOR VENDA_ITEM_GEN) FOR SEQ_VENDA_ITEM
END
/*
VENDA_ITEM
*/





/*
AF = AGGREGATE FUNCTION (CLR)

C = CHECK CONSTRAINT

D = DEFAULT (CONSTRAINT OR STAND-ALONE)

F = FOREIGN KEY CONSTRAINT

FN = SQL SCALAR FUNCTION

FS = ASSEMBLY (CLR) SCALAR-FUNCTION

FT = ASSEMBLY (CLR) TABLE-VALUED FUNCTION

IF = SQL INLINE TABLE-VALUED FUNCTION

IT = INTERNAL TABLE

P = SQL STORED PROCEDURE

PC = ASSEMBLY (CLR) STORED-PROCEDURE

PG = PLAN GUIDE

PK = PRIMARY KEY CONSTRAINT

R = RULE (OLD-STYLE, STAND-ALONE)

RF = REPLICATION-FILTER-PROCEDURE

S = SYSTEM BASE TABLE

SN = SYNONYM

SO = SEQUENCE OBJECT
*/

